export const CATEGORIES_SUCCESS = "CATEGORIES_SUCCESS";
export const CATEGORIES_ERROR = "CATEGORIES_ERROR";

export const TOGGLE_MENU = "TOGGLE_MENU";

export const PRODUCTS_SUCCESS = "PRODUCTS_SUCCESS";
export const PRODUCTS_ERROR = "PRODUCTS_ERROR";

export const SORT_BY_VALUE = 'SORT_BY_VALUE';
export const TOGGLE_DISCOUNT_FILTER = 'TOGGLE_DISCOUNT_FILTER';